/**
 * 连接配置 - IPC 通道
 */

export const CONNECTION = {
  OPENCODE_HEALTH: 'MAIN_OPENCODE__HEALTH',
  OPENCODE_CONNECT: 'MAIN_OPENCODE__CONNECT',
  OPENCODE_DISCONNECT: 'MAIN_OPENCODE__DISCONNECT',
  INIT_GET_STATUS: 'MAIN_INIT__GET_STATUS',
  CONFIG_GET: 'MAIN_OPENCODE__CONFIG_GET',
  CONFIG_PROVIDERS: 'MAIN_OPENCODE__CONFIG_PROVIDERS',
} as const;
