/**
 * MCP 相关 IPC 通道
 */

export const MCP = {
  MCP_LIST: 'MAIN_MCP__LIST',
  MCP_ADD: 'MAIN_MCP__ADD',
  MCP_REMOVE: 'MAIN_MCP__REMOVE',
  MCP_TOGGLE: 'MAIN_MCP__TOGGLE',
  MCP_STATUS: 'MAIN_MCP__STATUS',
  MCP_AUTH_START: 'MAIN_MCP__AUTH_START',
  MCP_AUTH_REMOVE: 'MAIN_MCP__AUTH_REMOVE',
  MCP_RECONNECT: 'MAIN_MCP__RECONNECT',
} as const;
