/**
 * 会话管理 - IPC 通道
 */

export const SESSION = {
  OPENCODE_SESSION_CREATE: 'MAIN_OPENCODE__SESSION_CREATE',
  OPENCODE_SESSION_LIST: 'MAIN_OPENCODE__SESSION_LIST',
  OPENCODE_SESSION_GET: 'MAIN_OPENCODE__SESSION_GET',
  OPENCODE_SESSION_DELETE: 'MAIN_OPENCODE__SESSION_DELETE',
} as const;
